variables:
  DOCKER_IMAGE_VERSION: '27.3.1'
  SBT_VERSION: "1.10.3"
  JAVA_VERSION: "21"
  IMAGE_VERSION: "${JAVA_VERSION}-${SBT_VERSION}"
  IMAGE_TAG: ${CI_REGISTRY}/examples/scala/java-with-sbt:${IMAGE_VERSION}

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
  - test

#
# Build the rocky-linux/java/sbt image on gitlab so that we get x86-64 versions of everything.
#
build-image:
  when: manual
  stage: build
  image: docker:${DOCKER_IMAGE_VERSION}
  services:
    - name: docker:${DOCKER_IMAGE_VERSION}-dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - echo "${IMAGE_TAG}"
    - docker build --file Dockerfile-test --tag ${IMAGE_TAG} .
    - docker push ${IMAGE_TAG}


unit-test-job:
  image: ${IMAGE_TAG}
  stage: test
  artifacts:
    when: always
    reports:
      junit: target/test-reports/*.xml
  script:
    - sbt test
