#
# image source: https://hub.docker.com/_/rockylinux
#
FROM rockylinux:9

# installing all the binaries
RUN yum -y update && yum install -y tar && yum clean all

RUN mkdir -p /opt/java \
    && cd /opt/java \
    && curl -LO https://corretto.aws/downloads/latest/amazon-corretto-21-x64-linux-jdk.tar.gz \
    && tar --strip-components=1 --extract --verbose --file /opt/java/amazon-corretto-21-x64-linux-jdk.tar.gz \
    && rm -rf amazon-corretto-21-x64-linux-jdk.tar.gz

RUN mkdir -p /opt \
    && cd /opt \
    && curl -LO https://github.com/sbt/sbt/releases/download/v1.10.3/sbt-1.10.3.tgz \
    && tar -xvf sbt-1.10.3.tgz \
    && rm -rf sbt-1.10.3.tgz

ENV JAVA_HOME="/opt/java"
ENV SBT_HOME="/opt/sbt"

ENV PATH="${JAVA_HOME}/bin:${SBT_HOME}/bin:/root/.local/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

